# -*- coding: utf-8 -*-
"""K_Means_Clustering_casestudy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eRIWemoJPyzF4wEPLgoHU4h9pgaoeJ2C
"""

# Import necessary libraries
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Load the dataset
from google.colab import files
uploaded = files.upload()

# loading into a DataFrame
student_data = pd.read_csv(next(iter(uploaded)))

# Display the first few rows
student_data.head()

# Extract the relevant features (cgpa and iq)
X = student_data[['cgpa', 'iq']]

# Apply K-means clustering with 2 clusters
kmeans = KMeans(n_clusters=2, random_state=0)
student_data['cluster'] = kmeans.fit_predict(X)

# Visualize the clusters
plt.scatter(student_data['cgpa'], student_data['iq'], c=student_data['cluster'], cmap='viridis')
plt.xlabel('CGPA')
plt.ylabel('IQ')
plt.title('K-means Clustering of Students based on CGPA and IQ')
plt.show()

# Print cluster centers
print("Cluster centers:")
print(kmeans.cluster_centers_)

