# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJ0MBtDV2E0z6Q8LWNTTu-Qjf-u5yv8X
"""

import pandas as pd

dataset = pd.read_csv("/content/Iris.csv")

dataset

#seprating the independent variables
x=dataset.iloc[:,0:5]

x

#seprating the dependent variable
y = dataset.iloc[:,5]

y

#for spiltting the dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)

len(X_train)

len(X_test)

from sklearn.svm import SVC

model = SVC(kernel = 'linear')

model.fit(X_train,y_train)

model.predict(X_test)

X_test

#Accuracy of the model
model.score(X_test,y_test)